### PR TITLE
Release v0.2.11 

### PR DESCRIPTION
**Pull request by lukasol**

### CODE REVIEW

**Review by mariusves — APPROVED** [review]
looks good to me! I think most of the changes have already been merged by @nesnoj

**Comment by ulfmueller** [comment]
I do not know if @nesnoj was already finished with preparing for v0.3.0 (I think he wants it inline with the upcoming dp release v0.3). Therefore (if there is no spontaneous reaction from @nesnoj )  I would suggest to name this release v0.2.11 and change this 617161c7dc7b8b8f97d273598acabdd00e793da1

**Comment by lukasol** [comment]
okay, yes I was wondering about the numbering of the tags. I will change it.

**Comment by nesnoj** [comment]
If you plan to do a release v0.2.11 you did it just the right way..
If it is a temporary solution you do not intend to release prior to v0.3 you may keep the v0.3.0 in the setup.py

@lukasol: Concerning the tags: See [HowTo](https://github.com/openego/ego.io/wiki/How-to-release) in the Wiki :)

**Pull request merged**
