### PR TITLE
new release v0.2.10

### PR DESCRIPTION
**Pull request by nesnoj**
I'd like to make a new release with updated DB tables, config creator and DB connection provider.

With this release u can just do
```
from egoio.tools.db import connection

conn = connection(section=...)
Session = sessionmaker(bind=conn)
session = Session()
```
If the DB config file `~/.egoio/config.ini` does not exist, it will ask you to create it with provided host, user, ...
@ulfmueller 
@gplssm 
@IlkaCu 
@lukasol 

If there're no objections, I will merge it and create a new release on 30.08.

### CODE REVIEW

**Comment by nesnoj** [comment]
I messed up the merge, there were some duplicate definitions which made SQLA crash.
Fixed in ce06fc922e7bca7aee1143929a4b4e7c9650c813 and tested.
Ready for merge?

**Review by nesnoj — COMMENTED** [review]
Concerning f83970aa2e386119dd1c58757e91bd64a648b75f @mariusves:
These new columns have not been applied to the DB, have they?
I still see the old names `start_step`, `end_step` only..

**Comment by mariusves** [comment]
Changes are live on the DB as of now @nesnoj

**Comment by nesnoj** [comment]
Done.
Due to a bug I had to create a second release [v0.2.10.post1](https://github.com/openego/ego.io/releases/tag/v0.2.10.post1).
Available via PYPI.

**Pull request merged**
