### PR TITLE
Release/v0.4.0

### PR DESCRIPTION
**Pull request by gplssm**
Use the branch release/v0.4.0 to test.

### CODE REVIEW

**Comment by gplssm** [comment]
@ulfmueller I'm not sure if you got notified by the review request. Now, you should be notified. Please accept the PR once you can verify a successful run with eTraGo.

**Comment by ulfmueller** [comment]
sorry just started checking. Just got this error:

InvalidRequestError: When initializing mapper Mapper|EgoDemandPfLoadSingle|ego_demand_pf_load_single, expression 'EgoGridPfHvBu' failed to locate a name ("name 'EgoGridPfHvBu' is not defined"). If this is a class name, consider adding this relationship() to the <class 'egoio.db_tables.model_draft.EgoDemandPfLoadSingle'> class after both dependent classes have been defined.

seems like a bu bus thing... will look for it right now...

**Comment by ulfmueller** [comment]
what I could check works fine now. So the basic stuff of eTraGo works fine. I could not check some rather new functionalities for certain reasons. I would approve it now anyways. If some problems occur when being able to test them I would just create a 0.4.1 release.

**Review by ulfmueller — APPROVED** [review]

**Comment by gplssm** [comment]
Thanks a lot for your effort and the quick reply. I agree with backdoor of v0.4.1.

I'll update the default config.ini creator in ego.io according to the needs of the dialect option. Do you want to test it too @ulfmueller ? Otherwise, I'll test it with eDisGo/ding0 which should cover all needs of eTraGo as well...

**Comment by gplssm** [comment]
Ok, my changes have been minimal. No need to be tested by U

**Pull request merged**
