### PR TITLE
Fix/schema rename

### PR DESCRIPTION
**Pull request by Ludee**
https://github.com/openego/data_processing/issues/142
https://github.com/openego/ego.io/issues/25

### CODE REVIEW

**Comment by Ludee** [comment]
schema renaming completed. see https://github.com/openego/data_processing/issues/142
we can merge this pull if you approve!? @gplssm

**Comment by Ludee** [comment]
Also changed class names and table names!

**Comment by nesnoj** [comment]
@Ludee I don't see that there's a need to upgrade since everything will be upgraded anyway when running sqlacodegen..

**Comment by Ludee** [comment]
OK, Then is this branch obsolete or do we just merge it anyway?

**Comment by nesnoj** [comment]
Yes, it is obsolete. I just created a PR for v0.2.10, see #30

**Pull request closed without merging**
